### ISSUE TITLE
Minor issue with config.json

### ISSUE THREAD

**Issue by Ex-Opera** [astrapy/Astra.Nuker#21]
Minor issue with the config.json file since pfp_url is missing from there could be easily mitigated by adding it there
```
Traceback (most recent call last):
  File "/home/.../AstraNuker/nuker.py", line 28, in <module>
    config = load_config()
  File "/home/.../AstraNuker/nuker.py", line 26, in load_config
    return Config(**config_data)
TypeError: Config.__init__() missing 1 required positional argument: 'pfp_url'
```

**Comment by astrapy** [comment]
{ 
    "nuke_on_join": "true",  
    "rename_guild": "y",
    "channel_names": "y",
    "text": "@everyone Should've expected this =[ https://discord.gg/A5XW5RwMM4 \nhttps://github.com/astrapy",
    "token": "",
    "pfp_url": "link"
}

**Comment by Ex-Opera** [comment]
@astrapy It would be nice if you made this change in the repo itself.
